EXTRA_CFLAGS += -Iarch/arm/mach-msm
obj-$(CONFIG_LGE_HEADSET_2GPIO) += lge_gpio_h2w.o
obj-$(CONFIG_LGE_SWITCH_GPIO) += lge_gpio_switch.o
obj-$(CONFIG_LGE_PROC_COMM) += lge_proc_comm.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-mmc.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-wlan.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-snd.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-panel.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-bt.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-camera.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-input.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-misc.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-pm.o
#obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-vibrator.o
obj-$(CONFIG_MACH_MSM7X27_SWIFT) += board-swift-headset.o

obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-mmc.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-snd.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-panel.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-bt.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-camera.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-input.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-misc.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-pm.o

obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-mmc.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-snd.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-panel.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-bt.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-camera.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-input.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-misc.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-pm.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += lge_errorhandler.o #LGE_CHANGE [blue.park@lge.com] 2009-04-04 <For Error Handler>
obj-$(CONFIG_MACH_MSM7X27_PECAN) += lge_temp.o # LGE_CHANGE neo.kang@lge.com just for Line PV. It will be removed
obj-$(CONFIG_MACH_MSM7X27_PECAN) += lge_mtd_direct_access.o # LGE_CHANGE neo.kang@lge.com just for Line PV. It will be removed.

obj-$(CONFIG_MACH_LGE) += devices_lge.o


